services:
  wod-booker:
    build: .
    volumes:
      - sqlite_data:/app/db
      - ./classes.toml:/app/classes.toml:ro
    restart: always
    environment:
      - DB_PATH=/app/db/bookings.db

volumes:
  sqlite_data: